apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect-template.fullname" . }}-connect
  labels:
    {{- include "kafka-connect-template.labels" . | nindent 4 }}
type: Opaque
data:
{{ (tpl (.Files.Glob "config/*.json").AsConfig .) | indent 2 }}
