apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect-template.fullname" . }}
  labels:
    {{- include "kafka-connect-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-connect-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka-connect-template.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kafka-connect-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          #- name: CONNECT_PLUGIN_PATH
          #  value: "/usr/share/java" #default for confluent image
          - name: CONNECT_BOOTSTRAP_SERVERS
            value: {{ .Values.bootstrapServers }}
          - name: CONNECT_GROUP_ID
            value: {{ include "kafka-connect-template.fullname" . }}
          - name: CONNECT_CONFIG_STORAGE_TOPIC
            value: {{ .Values.configStorageTopic }}
          - name: CONNECT_OFFSET_STORAGE_TOPIC
            value: {{ .Values.offsetStorageTopic }}
          - name: CONNECT_STATUS_STORAGE_TOPIC
            value: {{ .Values.statusStorageTopic }}
          - name: CONNECT_KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_VALUE_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_INTERNAL_KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_INTERNAL_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_REST_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONNECT_REST_PORT
            value: "8083"
          - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
            value: "true"
          - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
            value: "true"
          - name: CONNECT_SSL_PROTOCOL
            value: "TLSv1.2"
          - name: CONNECT_SECURITY_PROTOCOL
            value: "SASL_SSL"
          - name: CONNECT_SSL_TRUSTSTORE_LOCATION
            value: "{{ .Values.eventstreamsTruststorePath }}"
          - name: CONNECT_SSL_TRUSTSTORE_PASSWORD
            value: "{{ .Values.eventstreamsTruststorePassword }}"
          - name: CONNECT_SASL_MECHANISM
            value: "PLAIN"
          - name: CONNECT_SASL_JAAS_CONFIG
            value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"token\" password=\"{{ .Values.eventstreamsApiKey }}\";"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: {{ include "kafka-connect-template.fullname" . }}-aws
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: {{ include "kafka-connect-template.fullname" . }}-aws
        volumeMounts:
        - name: kafka-connect-properties
          mountPath: "/opt/kafka/config"
          readOnly: true
        - name: eventstreams-truststore
          mountPath: "{{ .Values.eventstreamsTruststorePath | dir }}"
          readOnly: true
          optional: true
        ports:
          - name: http
            containerPort: 8083
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /connector-plugins
            port: http
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /connector-plugins
            port: http
          initialDelaySeconds: 30
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: kafka-connect-properties
        secret:
          secretName: {{ include "kafka-connect-template.fullname" . }}-connect
      - name: eventstreams-truststore
        secret:
          secretName: {{ include "kafka-connect-template.fullname" . }}-eventstreams
      - name: aws-credentials
        secret:
          secretName: {{ include "kafka-connect-template.fullname" . }}-aws
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
