apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-connect-template.fullname" . }}-eventstreams
  labels:
    {{- include "kafka-connect-template.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "config/*.jks").AsSecrets | indent 2 }}
