apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-connect-template.fullname" . }}-aws
  labels:
    {{- include "kafka-connect-template.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.awsAccessKeyId | b64enc }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.awsSecretAccessKey | b64enc }}"
