{{- $values := .Values -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-connect-template.fullname" . }}-connect
  labels:
    {{- include "kafka-connect-template.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $path, $bytes := .Files.Glob "config/*.properties" }}
{{ base $path | indent 2 -}}: '{{- tpl ($.Files.Get $path) $ | b64enc -}}'
{{- end -}}
